language: node_js
sudo: false
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run serve &
  - npm test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
